server:
  port: 8100
spring:
  application:
    name: mall-gateway
#  profiles:
#    active: dev
  cloud:
    # nacos注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: loc
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id

#nacos配置中心
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: loc


management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: debug