#nacos:
#  config:
#    namespace: loc
#    server-addr: 127.0.0.1:8848
#spring:
#  main:
#    allow-bean-definition-overriding: true
#  cloud:
#    nacos:
#      config:
#        file-extension: yaml #指定配置文件类型为yaml文件
logging:
  level:
    org.springframework.cloud.gateway: debug
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8100
spring:
  application:
    name: mall_gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: loc
    gateway:
      discovery:
        locator:
          enabled: true  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          lower-case-service-id: true  #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了