nacos:
  config:
    namespace: dev
    server-addr: 172.17.0.6:8848
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      config:
        file-extension: yaml #指定配置文件类型为yaml文件
