nacos:
  config:
    namespace: loc
    server-addr: 127.0.0.1:8848
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      config:
        file-extension: yaml #指定配置文件类型为yaml文件
